In [1]:
import os, os.path

print("Events:",len([name for name in os.listdir('data/events')]))
print("Lineups:",len([name for name in os.listdir('data/lineups')]))
print("Matches:",sum([len(os.listdir('data/matches/'+dir)) for dir in os.listdir('data/matches')]))
print("360:",len([name for name in os.listdir('data/three-sixty')]))

Events: 3433
Lineups: 3433
Matches: 74
360: 295

In [2]:
import json

# load matches from individual seasons
allSeasons = []

for dir in os.listdir('data/matches'):
    for f in os.listdir('data/matches/'+dir):
        with open('data/matches/'+dir+'/'+f) as season:
            seasonDict = json.load(season)
            allSeasons.append(seasonDict)

allMatches = []

for season in allSeasons:
    for match in season:
        allMatches.append(match)

In [3]:
import pandas as pd

matchesDF = pd.DataFrame(allMatches)

In [4]:
# clean dataframe
matchesDF = matchesDF.fillna("")
matchesDF

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,metadata,match_week,competition_stage,stadium,referee
0,3887188,1989-05-03,21:30:00.000,"{'competition_id': 35, 'country_name': 'Europe...","{'season_id': 75, 'season_name': '1988/1989'}","{'home_team_id': 227, 'home_team_name': 'Napol...","{'away_team_id': 174, 'away_team_name': 'VfB S...",2,1,available,unscheduled,2023-06-18T19:28:39.443883,,"{'data_version': '1.1.0', 'shot_fidelity_versi...",12,"{'id': 26, 'name': 'Final'}","{'id': 117450, 'name': 'Stadio Diego Armando M...","{'id': 1009054, 'name': 'Gerasimos Germanakos'..."
1,3750244,1989-04-05,,"{'competition_id': 35, 'country_name': 'Europe...","{'season_id': 75, 'season_name': '1988/1989'}","{'home_team_id': 227, 'home_team_name': 'Napol...","{'away_team_id': 169, 'away_team_name': 'Bayer...",2,0,available,scheduled,2020-07-29T05:00,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",10,"{'id': 15, 'name': 'Semi-finals'}","{'id': 117450, 'name': 'Stadio Diego Armando M...","{'id': 1932, 'name': 'Michel Vautrot', 'countr..."
2,3750245,1989-03-15,20:30:00.000,"{'competition_id': 35, 'country_name': 'Europe...","{'season_id': 75, 'season_name': '1988/1989'}","{'home_team_id': 227, 'home_team_name': 'Napol...","{'away_team_id': 1076, 'away_team_name': 'Juve...",3,0,available,scheduled,2023-05-22T16:05:43.468317,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",9,"{'id': 11, 'name': 'Quarter-finals'}","{'id': 117450, 'name': 'Stadio Diego Armando M...","{'id': 1929, 'name': 'Siegfried Kirschen', 'co..."
3,3827767,2022-03-20,16:00:00.000,"{'competition_id': 1238, 'country_name': 'Indi...","{'season_id': 108, 'season_name': '2021/2022'}","{'home_team_id': 7289, 'home_team_name': 'Hyde...","{'away_team_id': 7283, 'away_team_name': 'Kera...",1,1,available,unscheduled,2022-04-14T17:33:06.627987,,"{'data_version': '1.1.0', 'shot_fidelity_versi...",25,"{'id': 74, 'name': 'Championship - Final'}","{'id': 1000400, 'name': 'Pandit Jawaharlal Neh...","{'id': 1004906, 'name': 'Crystal John', 'count..."
4,3827335,2022-03-15,16:00:00.000,"{'competition_id': 1238, 'country_name': 'Indi...","{'season_id': 108, 'season_name': '2021/2022'}","{'home_team_id': 7283, 'home_team_name': 'Kera...","{'away_team_id': 2021, 'away_team_name': 'Jams...",1,1,available,unscheduled,2022-05-17T22:00:48.247246,,"{'data_version': '1.1.0', 'shot_fidelity_versi...",24,"{'id': 158, 'name': 'Play-offs - Semi-Finals'}","{'id': 1000401, 'name': 'Tilak Maidan Stadium'...","{'id': 1004863, 'name': 'Harish Kundu', 'count..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3428,3749108,2003-08-27,20:45:00.000,"{'competition_id': 2, 'country_name': 'England...","{'season_id': 44, 'season_name': '2003/2004'}","{'home_team_id': 1, 'home_team_name': 'Arsenal...","{'away_team_id': 59, 'away_team_name': 'Aston ...",2,0,available,processing,2023-01-28T22:32:37.443603,2021-06-12T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",3,"{'id': 1, 'name': 'Regular Season'}",,
3429,3749153,2004-01-10,16:00:00.000,"{'competition_id': 2, 'country_name': 'England...","{'season_id': 44, 'season_name': '2003/2004'}","{'home_team_id': 1, 'home_team_name': 'Arsenal...","{'away_team_id': 47, 'away_team_name': 'Middle...",4,1,available,scheduled,2020-08-30T08:12:14.579037,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",21,"{'id': 1, 'name': 'Regular Season'}","{'id': 1000243, 'name': 'Highbury Stadium', 'c...",
3430,3749403,2004-03-20,16:00:00.000,"{'competition_id': 2, 'country_name': 'England...","{'season_id': 44, 'season_name': '2003/2004'}","{'home_team_id': 1, 'home_team_name': 'Arsenal...","{'away_team_id': 328, 'away_team_name': 'Bolto...",2,1,available,scheduled,2020-07-29T05:00,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",29,"{'id': 1, 'name': 'Regular Season'}","{'id': 1000243, 'name': 'Highbury Stadium', 'c...",
3431,3749526,2003-10-26,15:00:00.000,"{'competition_id': 2, 'country_name': 'England...","{'season_id': 44, 'season_name': '2003/2004'}","{'home_team_id': 75, 'home_team_name': 'Charlt...","{'away_team_id': 1, 'away_team_name': 'Arsenal...",1,1,available,scheduled,2020-07-29T05:00,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",1,"{'id': 1, 'name': 'Regular Season'}","{'id': 31, 'name': 'The Valley', 'country': {'...",
3432,3749431,2004-04-11,17:05:00.000,"{'competition_id': 2, 'country_name': 'England...","{'season_id': 44, 'season_name': '2003/2004'}","{'home_team_id': 37, 'home_team_name': 'Newcas...","{'away_team_id': 1, 'away_team_name': 'Arsenal...",0,0,available,scheduled,2020-07-29T05:00,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",2,"{'id': 1, 'name': 'Regular Season'}","{'id': 4674, 'name': 'St. James'' Park', 'coun...",

In [5]:
matchesDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3433 entries, 0 to 3432
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   match_id           3433 non-null   int64
 1   match_date         3433 non-null   object
 2   kick_off           3433 non-null   object
 3   competition        3433 non-null   object
 4   season             3433 non-null   object
 5   home_team          3433 non-null   object
 6   away_team          3433 non-null   object
 7   home_score         3433 non-null   int64
 8   away_score         3433 non-null   int64
 9   match_status       3433 non-null   object
 10  match_status_360   3433 non-null   object
 11  last_updated       3433 non-null   object
 12  last_updated_360   3433 non-null   object
 13  metadata           3433 non-null   object
 14  match_week         3433 non-null   int64
 15  competition_stage  3433 non-null   object
 16  stadium            3433 non-null   object
 17  referee            3433 non-null   object
dtypes: int64(4), object(14)
memory usage: 482.9+ KB

In [6]:
#convert cols to correct type
matchesDF["match_date"] = pd.to_datetime(matchesDF["match_date"], format='ISO8601')

In [7]:
matchesDF["last_updated"] = pd.to_datetime(matchesDF["last_updated"], format='ISO8601') 
matchesDF["last_updated_360"] = pd.to_datetime(matchesDF["last_updated_360"], format='ISO8601') 
matchesDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3433 entries, 0 to 3432
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   match_id           3433 non-null   int64
 1   match_date         3433 non-null   datetime64[ns]
 2   kick_off           3433 non-null   object
 3   competition        3433 non-null   object
 4   season             3433 non-null   object
 5   home_team          3433 non-null   object
 6   away_team          3433 non-null   object
 7   home_score         3433 non-null   int64
 8   away_score         3433 non-null   int64
 9   match_status       3433 non-null   object
 10  match_status_360   3433 non-null   object
 11  last_updated       3433 non-null   datetime64[ns]
 12  last_updated_360   1797 non-null   datetime64[ns]
 13  metadata           3433 non-null   object
 14  match_week         3433 non-null   int64
 15  competition_stage  3433 non-null   object
 16  stadium            3433 non-null   object
 17  referee            3433 non-null   object
dtypes: datetime64[ns](3), int64(4), object(11)
memory usage: 482.9+ KB

In [8]:
matchesDF = matchesDF.drop(columns="kick_off")

In [9]:
matchesDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3433 entries, 0 to 3432
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   match_id           3433 non-null   int64
 1   match_date         3433 non-null   datetime64[ns]
 2   competition        3433 non-null   object
 3   season             3433 non-null   object
 4   home_team          3433 non-null   object
 5   away_team          3433 non-null   object
 6   home_score         3433 non-null   int64
 7   away_score         3433 non-null   int64
 8   match_status       3433 non-null   object
 9   match_status_360   3433 non-null   object
 10  last_updated       3433 non-null   datetime64[ns]
 11  last_updated_360   1797 non-null   datetime64[ns]
 12  metadata           3433 non-null   object
 13  match_week         3433 non-null   int64
 14  competition_stage  3433 non-null   object
 15  stadium            3433 non-null   object
 16  referee            3433 non-null   object
dtypes: datetime64[ns](3), int64(4), object(10)
memory usage: 456.1+ KB

In [11]:
# 360 files json generation
allThreeSixty = []

for file in os.listdir('data/three-sixty'):
    with open('data/three-sixty/'+file, 'r') as event:
        try:
            eventDict = json.load(event)
            allThreeSixty.append(eventDict)
        except:
            with open("panda_360_unread.txt", 'a') as log:
                    log.write('data/three-sixty/'+file+'\n')

In [13]:
threeSixtyDF = [pd.DataFrame(event) for event in allThreeSixty]
threeSixtyDF[0].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3811 entries, 0 to 3810
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   event_uuid    3811 non-null   object
 1   visible_area  3811 non-null   object
 2   freeze_frame  3811 non-null   object
dtypes: object(3)
memory usage: 89.4+ KB

In [14]:
threeSixtyDF[0].head()

,event_uuid,visible_area,freeze_frame
0,75d6cc25-b03b-44e0-9c50-99a7e3c47315,"[29.574167858721, 80.0, 47.7992071074168, 0.0,...","[{'teammate': True, 'actor': False, 'keeper': ..."
1,ec457cc8-050c-4884-abbc-1e85bc3c83dc,"[29.5261908068648, 80.0, 47.3846276547738, 0.0...","[{'teammate': True, 'actor': False, 'keeper': ..."
2,246b93aa-3831-4b07-a51e-b6ba578e60d5,"[27.6350829489137, 80.0, 45.4935197968227, 0.0...","[{'teammate': True, 'actor': False, 'keeper': ..."
3,eda20fee-cab0-4094-aba3-ae286ef64004,"[13.8331181325244, 80.0, 40.2628933325614, 6.1...","[{'teammate': True, 'actor': True, 'keeper': F..."
4,e8a3f021-76da-443b-9a1d-c5857c486493,"[13.8331181325244, 80.0, 40.2628933325614, 6.1...","[{'teammate': True, 'actor': True, 'keeper': F..."